config/routes.rb
Rails.application.routes.draw do

  resources :sessions
  resources :replies
  resources :inquiries
  resources :houses
  resources :users
  resources :companies

  root'users#new'
  get 'sessions/new'
  get 'login', to: 'sessions#new'
  get 'signup', to: 'users#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'houses/search', to: 'houses#search'
  # root'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: [:show, :edit, :update, :destroy]

  # GET /houses
  # GET /houses.json
  def index
    @houses = House.where(nil)
    puts params.inspect
    @houses = House.where(list_price: params[:listPriceLow]..params[:listPriceHigh]) if
        params[:listPriceLow].present? and params[:listPriceHigh].present?
    @houses = House.where(square_footage: params[:squareFootageLow]..params[:squareFootageHigh]) if
        params[:squareFootageLow].present? and params[:squareFootageHigh].present?
    @houses = House.where("location like ?", "#{params[:location]}%") if params[:location].present?
  end

  def search

  end

  # GET /houses/1
  # GET /houses/1.json
  def show
  end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(house_params)
    @house.update(user_id: current_user.id)
    @house.update(company_id: current_user.company_id)
    respond_to do |format|
      if @house.save
        format.html { redirect_to @house, notice: 'House was successfully created.' }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to houses_url, notice: 'House was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_params
      params.require(:house).permit(:user_id, :location, :square_footage, :year_built, :style, :list_price, :no_of_floors, :basement, :current_house_owner, :contact_info, :potential_buyers, :image, :listPriceLow, :listPriceHigh, :squareFootageLow, :squareFootageHigh, :company_id)
    end
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/_form.html.erb
<%= form_for @house, :html => {:multipart => true}  do |form| %>
  <% if house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
      <% house.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :house_location %>
  </div>

  <div class="field">
    <%= form.label :square_footage %>
    <%= form.number_field :square_footage, id: :house_square_footage %>
  </div>

  <div class="field">
    <%= form.label :year_built %>
    <%= form.number_field :year_built, id: :house_year_built %>
  </div>

  <div class="field">
    <%= form.label :style %>
    <%= form.text_field :style, id: :house_style %>
  </div>

  <div class="field">
    <%= form.label :list_price %>
    <%= form.number_field :list_price, id: :house_list_price %>
  </div>

  <div class="field">
    <%= form.label :no_of_floors %>
    <%= form.number_field :no_of_floors, id: :house_no_of_floors %>
  </div>

  <div class="field">
    <%= form.label :basement %>
    <%= form.check_box :basement, id: :house_basement %>
  </div>

  <div class="field">
    <%= form.label :current_house_owner %>
    <%= form.text_field :current_house_owner, id: :house_current_house_owner %>
  </div>

  <div class="field">
    <%= form.label :contact_info %>
    <%= form.text_field :contact_info, id: :house_contact_info %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :house_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/houses/_search.html.erb
<%= form_tag(houses_path, method: :get) do %>
  <div>
    List Price Low:
    <%= text_field_tag :listPriceLow, params[:listPriceLow] %>
    List Price High:
    <%= text_field_tag :listPriceHigh, params[:listPriceHigh] %>
    (Please include both low and high values.)
    <br><%= submit_tag 'Filter on List Price', name: nil %>
  </div>
  <div>
    Square Footage Low:
    <%= text_field_tag :squareFootageLow, params[:squareFootageLow] %>
    Square Footage High:
    <%= text_field_tag :squareFootageHigh, params[:squareFootageHigh]%>
    (Please include both low and high values.)
    <br><%= submit_tag 'Filter on List Price', name: nil %>
  </div>
  <div>
    Location:
    <%= text_field_tag :location, params[:location] %>
  <br><%= submit_tag 'Filter on Location', name: nil %>
  </div>
<% end %>
<br/>
<br/>

</section>

app/views/houses/edit.html.erb
<h1>Editing House</h1>

<%= render 'form', house: @house %>
<button><%= link_to 'Show', @house %></button> |
<button><%= link_to 'Back', houses_path %></button>

app/views/houses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Houses</h1>

<%= render 'houses/search' %>
<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Square Footage</th>
      <th>Year built</th>
      <th>Style</th>
      <th>List price</th>
      <th>No of floors</th>
      <th>Basement</th>
      <th>Current House Owner</th>
      <th>Contact Info</th>
      <% if current_user.role != "HouseHunter" %>
      <th>Potential buyers</th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
        <td><%= house.location %></td>
        <td><%= house.square_footage %></td>
        <td><%= house.year_built %></td>
        <td><%= house.style %></td>
        <td><%= house.list_price %></td>
        <td><%= house.no_of_floors %></td>
        <td><%= house.basement %></td>
        <td><%= house.current_house_owner %></td>
        <td><%= house.contact_info %></td>
        <%if current_user.role != "HouseHunter" %>
          <td><%= house.potential_buyers %></td>
        <%end %>
        <td><button><%= link_to 'Show', house %></button></td>
        <% if current_user.role == "HouseHunter" %>
        <td><button><%= link_to 'Submit Inquiry', new_inquiry_path(:id => house.id) %></button></td>
        <%end %>
        <!--% if current_user.role == "Realtor" %-->
        <td><button><%= link_to 'View House Inquiries', inquiries_path(:id => house.id) %></button></td>
        <!--% end %-->

          <% if current_user && ((current_user.role=="Realtor" && current_user.id == house.user_id) || current_user.role=="Admin") %>
        <td><button><%= link_to 'Edit', edit_house_path(house) %></button></td>
        <td><button><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
        <%end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user.role != "HouseHunter" %>
  <button><%= link_to 'New House', new_house_path %></button>
<%end %>
<button><%= link_to 'Back', current_user %></button>

app/views/houses/new.html.erb
<h1>Add a new House</h1>

<%= render 'form', house: @house %>

<button><%= link_to 'Back', houses_path %></button>
<button><%= link_to 'Home', current_user %></button>

app/views/houses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @house.location %>
</p>

<p>
  <strong>Square footage:</strong>
  <%= @house.square_footage %>
</p>

<p>
  <strong>Year built:</strong>
  <%= @house.year_built %>
</p>

<p>
  <strong>Style:</strong>
  <%= @house.style %>
</p>

<p>
  <strong>List price:</strong>
  <%= @house.list_price %>
</p>

<p>
  <strong>No of floors:</strong>
  <%= @house.no_of_floors %>
</p>

<p>
  <strong>Basement:</strong>
  <%= @house.basement %>
</p>

<p>
  <strong>Current house owner:</strong>
  <%= @house.current_house_owner %>
</p>

<p>
  <strong>Contact info:</strong>
  <%= @house.contact_info %>
</p>

<p>
  <strong>Pictures:</strong>
  <%= image_tag @house.image_url.to_s %>
</p>
<% if current_user.role != "HouseHunter" %>
<p>
  <strong>Potential buyers:</strong>
  <%= @house.potential_buyers %>
</p>
<% end %>
 <% if current_user && ((current_user.role=="Realtor" && current_user.id == @house.user_id) || current_user.role=="Admin") %>
  <button><%= link_to 'Edit', edit_house_path(@house) %></button>
<% end %>
<button><%= link_to 'Back', houses_path %></button>

<% if current_user.role == "HouseHunter" %>
<button><%= link_to 'Submit an Inquiry', new_inquiry_path %></button>
<td><button><%= link_to 'I am Interested!', House.update(@house.id, potential_buyers: current_user.name ) %></button></td>
<% end %>
<td><button><%= link_to 'View House Inquiries', inquiries_path %></button></td>
<button><%= link_to 'Home', current_user %></button>