config/routes.rb
Rails.application.routes.draw do

  resources :sessions
  resources :replies
  resources :inquiries
  resources :houses
  resources :users
  resources :companies

  root'users#new'
  get 'sessions/new'
  get 'login', to: 'sessions#new'
  get 'signup', to: 'users#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'houses/search', to: 'houses#search'
  # root'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
    validates :name, :role,:email, presence: true
   # validates :email #, uniqueness: true
    # validates :password, presence: true, allow_nil: true #, :if => :password # only validate if password changed!
    # attr_accessor :email , :password , :password_confirmation
  ROLE_LIST = ["Realtor", "HouseHunter"]
  CONTACT_METHOD = ["Phone","Text","Email"]

  def admin?
    self.role == "Admin"
  end

  def realter?
    self.role == "Realtor"
  end

  def hunter?
    self.role == "HouseHunter"
  end
  def find_realtor_by_company(id)
    @user = User.where("company_id == ? and users.role == ?", id, "Realtor")
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    # @id = current_user.id
    # puts "ID is #{@id}"
  end

  # GET /users/1
  # GET /users/1.json
  def show
    # 0@id = current_user.id
    # puts "ID is #{@id}"
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to '/login', notice: 'User was successfully created, Kindly Log In with the credentials.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      puts "User's Params: #{user_params}"
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :name, :password, :password_confirmation, :phone, :contactmethod, :role, :company_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |form| %>
  <% if @user.errors.any? %>
    <h2>Form is invalid</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, id: :user_email, :placeholder => 'Email', class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name, :placeholder => 'Name', class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password, :placeholder => 'Password (minimum 6 characters)', class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :confirm_password %>
    <%= form.password_field :password_confirmation, id: :user_password, :placeholder => 'Confirm Password (minimum 6 characters)', class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :role %>
    <%= form.select :role, User::ROLE_LIST, id: :user_role, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :user_phone %>
  </div>

  <div class="field">
    <%= form.label :contactmethod %>
    <%= form.select :contactmethod, User::CONTACT_METHOD, id: :user_contactmethod %>
  </div>

  <!--% if current_user && current_user.role == "Realtor" %-->
    <div class="field">
      <%= form.label :company_id %>
      <%= form.select :company_id, options_for_select(Company.all.map {|c| [c.name, c.id] if c.name != "none"}), id: :company_id %>
      Choose Real Estate Company if you are a realtor
    </div>
  <!--%end%-->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user, form_for: :edit %>

<button><%= link_to 'Show', @user %></button> |
<button><%= link_to 'Back', user_path %></button>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Phone</th>
      <th>Contact Method</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= user.phone %></td>
        <td><%= user.contactmethod %></td>
        <td><%= user.role %></td>
        <td><button><%= link_to 'Show', user %></button></td>
        <td><button><%= link_to 'Edit', edit_user_path(user) %></button></td>
        <td><%= button_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button><%= link_to 'New User', new_user_path %></button>
<button><%= link_to 'Back', current_user %></button>

app/views/users/new.html.erb
<h4>Please fill up the below form to sign up as a new user</h4>
<div class="login">
   <div class="container">
     <div class="form">
       <%= render 'form', user: @user, form_for: :signup %>
       <button><%= link_to 'Back', current_user %></button>
     </div>
   </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<% if current_user && current_user.role == "HouseHunter"%>
<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Contactmethod:</strong>
  <%= @user.contactmethod %>
</p>
<% end %>

<% if current_user && current_user.role == "Realtor"%>
  <p>
    <strong>Company:</strong>
    <%= Company.all.find(@user.company_id).name %>
  </p>
<%end %>
<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<button><%= link_to 'Edit', edit_user_path(@user) %></button> |
<button><%= link_to 'Houses', houses_url %></button> |
<% if current_user && (current_user.role == "Realtor" || current_user.role == "Admin")%>
  <button><%= link_to 'Real Estate Companies', companies_url %></button> |
<% end %>
<% if current_user && current_user.role == "Admin" %>
  <button><%= link_to 'New User', new_user_path %></button> |
  <button><%= link_to 'List of Users', users_url %></button>
  <button><%= link_to 'Back', users_path %></button> |
<% end %>