config/routes.rb
Rails.application.routes.draw do

  resources :sessions
  resources :replies
  resources :inquiries
  resources :houses
  resources :users
  resources :companies

  root'users#new'
  get 'sessions/new'
  get 'login', to: 'sessions#new'
  get 'signup', to: 'users#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'houses/search', to: 'houses#search'
  # root'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users
  # has_many :houses
  validates :name, presence: true
  validates :website, presence: true
  validates :size, presence: true
  validates :founded, presence: true
  validates :revenue, presence: true
  validates :synopsis, presence: true

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :website, :address, :size, :founded, :revenue, :synopsis)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :company_name %>
  </div>

  <div class="field">
    <%= form.label :website %>
    <%= form.text_field :website, id: :company_website %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :company_address %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size, id: :company_size %>
  </div>

  <div class="field">
    <%= form.label :founded %>
    <%= form.number_field :founded, id: :company_founded %>
  </div>

  <div class="field">
    <%= form.label :revenue %>
    <%= form.text_field :revenue, id: :company_revenue %>
  </div>

  <div class="field">
    <%= form.label :synopsis %>
    <%= form.text_area :synopsis, id: :company_synopsis %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<button><%= link_to 'Show', @company %></button> |
<button><%= link_to 'Back', companies_path %></button>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Real Estate Companies</h3>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Website</th>
      <th>Address</th>
      <th>Size</th>
      <th>Founded</th>
      <th>Revenue</th>
      <th>Synopsis</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.website %></td>
        <td><%= company.address %></td>
        <td><%= company.size %></td>
        <td><%= company.founded %></td>
        <td><%= company.revenue %></td>
        <td><%= company.synopsis %></td>

        <% if current_user && ((current_user.role=="Realtor" && current_user.company_id == company.id) || current_user.role=="Admin") %>
          <td><button><%= link_to 'Show', company %></button></td>
          <td><button><%= link_to 'Edit', edit_company_path(company) %></button></td>
          <td><button><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
          <%end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button><%= link_to 'New Company', new_company_path %></button>
<button><%= link_to 'Back', current_user %></button>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<button><%= link_to 'Back', current_user %></button>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Website:</strong>
  <%= @company.website %>
</p>

<p>
  <strong>Address:</strong>
  <%= @company.address %>
</p>

<p>
  <strong>Size:</strong>
  <%= @company.size %>
</p>

<p>
  <strong>Founded:</strong>
  <%= @company.founded %>
</p>

<p>
  <strong>Revenue:</strong>
  <%= @company.revenue %>
</p>

<p>
  <strong>Synopsis:</strong>
  <%= @company.synopsis %>
</p>

<button><%= link_to 'Edit', edit_company_path(@company) %></button> |
<button><%= link_to 'Back', companies_path %></button>