config/routes.rb
Rails.application.routes.draw do

  resources :sessions
  resources :replies
  resources :inquiries
  resources :houses
  resources :users
  resources :companies

  root'users#new'
  get 'sessions/new'
  get 'login', to: 'sessions#new'
  get 'signup', to: 'users#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'houses/search', to: 'houses#search'
  # root'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  belongs_to :house
  belongs_to :user
  has_many :replies
  validates :message_content, presence: true
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController

  before_action :set_inquiry, only: [:show, :edit, :update, :destroy]

  # GET /inquiries
  # GET /inquiries.json
  def index
    @@houseid = params[:id]
    if (current_user.role != "HouseHunter")
    @inquiries = Inquiry.where(house_id: @@houseid).order(created_at: :desc)
    end

    if(current_user.role == "HouseHunter")
     @inquiries = Inquiry.where(userid: current_user.id).order(created_at: :desc)
    end
  end

  # GET /inquiries/1
  # GET /inquiries/1.json
  def show

    @inquiry = Inquiry.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @inquiry }
    end
  end

  # GET /inquiries/new
  def new
    @inquiry = Inquiry.new
    @@houseid = params[:id]
  end

  # GET /inquiries/1/edit
  def edit
  end

  # POST /inquiries
  # POST /inquiries.json
  def create
    @inquiry = Inquiry.new(inquiry_params)
    puts "Inquiry Params: #{params}"
    @inquiry.update(user_id: current_user.id)
    @inquiry.update(house_id: @@houseid)

    respond_to do |format|
      if @inquiry.save
        format.html { redirect_to @inquiry, notice: 'Inquiry was successfully created.' }
        format.json { render :show, status: :created, location: @inquiry }
      else
        format.html { render :new }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inquiries/1
  # PATCH/PUT /inquiries/1.json
  def update
    respond_to do |format|
      if @inquiry.update(inquiry_params)
        format.html { redirect_to @inquiry, notice: 'Inquiry was successfully updated.' }
        format.json { render :show, status: :ok, location: @inquiry }
      else
        format.html { render :edit }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inquiries/1
  # DELETE /inquiries/1.json
  def destroy
    @inquiry.destroy
    respond_to do |format|
      format.html { redirect_to inquiries_url, notice: 'Inquiry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inquiry
      Inquiry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inquiry_params
      params.require(:inquiry).permit(:house_id, :user_id, :subject, :message_content)
    end
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/views/inquiries/_form.html.erb
<%= form_with(model: inquiry, local: true) do |form| %>
  <% if inquiry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inquiry.errors.count, "error") %> prohibited this inquiry from being saved:</h2>

      <ul>
      <% inquiry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject, id: :inquiry_subject %>
  </div>

  <div class="field">
    <%= form.label :message_content %>
    <%= form.text_area :message_content, id: :inquiry_message_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<button><%= link_to 'Home', current_user %></button>

app/views/inquiries/edit.html.erb
<h1>Editing Inquiry</h1>

<%= render 'form', inquiry: @inquiry %>

<%= link_to 'Show', @inquiry %> |
<%= link_to 'Back', inquiries_path %>

app/views/inquiries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inquiries</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Message content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inquiries.each do |inquiry| %>
      <tr>
        <td><%= inquiry.subject %></td>
        <td><%= inquiry.message_content %></td>
        <td><button><%= link_to 'Show', inquiry %></td></button>
        <%if current_user && current_user.role =="HouseHunter" %>
        <td><button><%= link_to 'Edit', edit_inquiry_path(inquiry) %></td></button>
      <%end %>
        <%if current_user && current_user.role =="Realtor" %>
          <td><button><%= link_to 'Post new Reply', new_reply_path(:id => inquiry.id) %></td></button>
        <%end %>
        <td><button><%= link_to 'View Reply', replies_path(:id => inquiry.id) %></td></button>
        <td><button><%= button_to 'Destroy', inquiry, method: :delete, data: { confirm: 'Are you sure?' } %></td></button>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button><%= link_to 'Home', current_user %></button>

app/views/inquiries/new.html.erb
<h1>New Inquiry</h1>

<%= render 'form', inquiry: @inquiry %>

<button><%= link_to 'Back', inquiries_path %></button>

app/views/inquiries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @inquiry.subject %>
</p>

<p>
  <strong>Message content:</strong>
  <%= @inquiry.message_content %>
</p>
<%if current_user && current_user.role =="HouseHunter" %>
<%= link_to 'Edit', edit_inquiry_path(@inquiry) %>
  <%end %>
<button><%= link_to 'Back', inquiries_path %></button>
<button><%= link_to 'Home', current_user %></button>